const PORT = process.env.PORT || 5000;
const API_BACKEND_HOST = "0.0.0.0";

const GOOGLE_CLOUD_LOCATION = process.env.GOOGLE_CLOUD_LOCATION;
const GOOGLE_CLOUD_PROJECT = process.env.GOOGLE_CLOUD_PROJECT;

if (!GOOGLE_CLOUD_PROJECT || !GOOGLE_CLOUD_LOCATION) {
  console.error("Missing GOOGLE_CLOUD_PROJECT or GOOGLE_CLOUD_LOCATION");
  process.exit(1);
} 
